### ISSUE TITLE
Unable to type into autocomplete field

### ISSUE THREAD

**Issue by jpshelley** [lejard-h/flutter_google_places_autocomplete#1]
Awesome work putting these libraries together!

The example app appears to run great on iOS. However when I try and use it in my own app my on screen keyboard no longer detects the keyboard strokes. The app is still responsive as I can back out of the autocomplete (and the debugger notices this by setting the future/prediction to null)

Have you seen this before and if so how would you fix it?

**Comment by lejard-h** [comment]
first time I see this, I don't have time to investigate right now, maybe this week end sorry

**Comment by jpshelley** [comment]
@lejard-h I finally got back to my side-project with flutter, turned out to be a simulator issue. After restarting it I haven't seen this anymore.
However the overlay mode does get hidden by the new iPhone X top notch. (Might be worth adding a new ticket for though)

**Comment by lejard-h** [comment]
Nice and sorry I did not have time too look at it, I will create an other issue for your bug, thanks you :)
