### ISSUE TITLE
Any idea why my given Location is ignored?

### ISSUE THREAD

**Issue by escamoteur** [lejard-h/flutter_google_places_autocomplete#11]
Although I pass a nearby locations the results are still worldwide.
Any idea?
Thanks

**Comment by lejard-h** [comment]
Hi, do you have a full example ? Did you check the official documentation ? (https://developers.google.com/places/android-api/autocomplete)

**Comment by escamoteur** [comment]
Hi,

I just found out that the problem was the missing radius prior to this PR https://github.com/lejard-h/flutter_google_places_autocomplete/pull/10

could you please update the package?

Thanks a lot for your work.

Thomas

P.S: I send you an invitation to the Flutter Slack

**Comment by lejard-h** [comment]
fixed in `0.0.5`
