### ISSUE TITLE
the overlay mode does get hidden by the new iPhone X top notch

### ISSUE THREAD

**Issue by lejard-h** [lejard-h/flutter_google_places_autocomplete#2]

**Comment by cad0p** [comment]
Facing same bug! Same code working on iPhone 8 Plus but not on iPhone 11 Pro Max!

Using overlay

How do I fix this?

**Comment by cad0p** [comment]
> Facing same bug! Same code working on iPhone 8 Plus but not on iPhone 11 Pro Max!
> 
> Using overlay
> 
> How do I fix this?

Well it now unexpectedly works

Thanks anyway lol
