### ISSUE TITLE
Get latitude and longitude

### ISSUE THREAD

**Issue by toregua** [lejard-h/flutter_google_places_autocomplete#3]
Hello,

Thank you very much for your flutter plugin.
I have a question and it is very important for me, is it possible to get the location of the user selected Prediction ?

Thanks in advance

**Comment by lejard-h** [comment]
I have just updated the library, and added an exemple [here](https://github.com/lejard-h/flutter_google_places_autocomplete/blob/master/example/lib/main.dart#L63)

Note that the library use google_maps_webservice library which directly refer to the official documentation for google maps web service.

**Comment by toregua** [comment]
Thank you for your quick answer.
It is exaclty what i need. For other be careful to have google_maps_webservice in 0.0.3 because 0.0.2 does not have geometry property on PlaceDetails
