### ISSUE TITLE
Provide feedback in case of error

### ISSUE THREAD

**Issue by giraldeau** [lejard-h/flutter_google_places_autocomplete#6]
I had an issue with my API key and got `REQUEST_DENIED`. In this situation, the UI does not update the result list and the user has no clue that an error occurs. What would be the best way to show/forward that error? Thanks!

**Comment by lejard-h** [comment]
Sorry, just saw this issue, In the last version (0.0.4) I added onError callback and also a way to build you own scaffold UI, see [here](https://github.com/lejard-h/flutter_google_places_autocomplete/blob/master/example/lib/main.dart#L99) the example.
